### ISSUE TITLE
Question: How to pass input parameters to the scripts as arguments

### ISSUE THREAD

**Issue by Chandu** [cloudify-cosmo/cloudify-script-plugin#16]
I want to pass an input parameter defined in my blueprint as a parameter to a script.
Is that possible?

**Comment by dankilman** [comment]
Hi, please use the cloudify-users group
https://groups.google.com/forum/#!forum/cloudify-users
and you shall be answered promptly!
I apologize for the hassle, I would just prefer the question/answer to appear there (hint: it is possible)

**Comment by Chandu** [comment]
@dankilman Thanks . I figured out. Used get_input intrinsic function. 

However just curious why the preference towards having the question posted in google groups to get an answer?

Isn't github also an equivalent (if not better) medium for these queries/questions?

**Comment by dankilman** [comment]
@Chandu Our code is currently scattered across many different repositories. While certain questions naturally relate to one repository, for some questions it's a big more vague and grouping it all in one place seems to make sense.

**Comment by Chandu** [comment]
@dankilman Got it. Thanks.
